/*
 * generated by Xtext
 */
package org.xtext.example.webgme;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MTLRuntimeModule extends org.xtext.example.webgme.AbstractMTLRuntimeModule {

}
