/*
* generated by Xtext
*/
package org.xtext.example.webgme;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MTLStandaloneSetup extends MTLStandaloneSetupGenerated{

	public static void doSetup() {
		new MTLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

