/**
 * generated by Xtext
 */
package org.xtext.example.webgme.ui.contentassist;

import org.xtext.example.webgme.ui.contentassist.AbstractMTLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MTLProposalProvider extends AbstractMTLProposalProvider {
}
