/*
* generated by Xtext
*/
package org.xtext.example.webgme.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.webgme.services.MTLGrammarAccess;

public class MTLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MTLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.webgme.parser.antlr.internal.InternalMTLParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.webgme.parser.antlr.internal.InternalMTLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MTLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MTLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
