/*
 * generated by Xtext
 */
package org.xtext.example.webgme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MTLUiModule extends org.xtext.example.webgme.ui.AbstractMTLUiModule {
	public MTLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
