/**
 * generated by Xtext
 */
package org.xtext.example.webgme.validation;

import org.xtext.example.webgme.validation.AbstractMTLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MTLValidator extends AbstractMTLValidator {
}
